CREATE TABLE pessoa (
	id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    imagem VARCHAR(255) NULL,
    create_at DATETIME NOT NULL,
    update_at DATETIME NOT NULL
);